SET WD=%2
SET USERNAME=%3
SET PROGRAM=%4
SET LINK=%5
SET PROGRAM=%PROGRAM:"=%
REM IF %WD:~-1%==\ SET WD=%WD:~0,-1%
IF NOT %1==INTENTION EXIT
TITLE EIC Chailoader - %PROGRAM%
SET DRIVELETTER=Q
SUBST %DRIVELETTER%: "%WD%\profiles\Meizikyn\%PROGRAM%"
SET USERPROFILE=C:\Users\Isolation
SET TEMP=%USERPROFILE%\AppData\Local\Temp
SET TMP=%USERPROFILE%\AppData\Local\Temp
%USERPROFILE%\Desktop\%LINK%.lnk
pause